.github/workflows/default_test_security-scan-workflow.yml, .github/workflows/inputs_test_security-scan-workflow.yml, .github/workflows/platsec-security-scan-reusable-workflow.yml
- The reusable workflow has been updated to use the `anchore/scan-action/download-grype` GH Action. Which allow us to properly control the version of Grype we use for security scanning. 
- Additionally, the workflow tests have been split into two files to more accurately represent Git Repos that need to scan mutiple Dockerfiles.
=> Add Grype Version Control

.github/workflows/platsec-security-scan-reusable-workflow.yml, .github/workflows/test_security-scan-workflow.yml, Dockerfile, security-workflow-template.yml, test/Dockerfile.base
Added the following new `Input Variables` to allow for more granular control by the App Teams.
- `only_fixed` | *(default: true)* | Set whether to output only vulnerabilities with fixes.
- `fail_on_vulns` | *(default: true)* |  Set whether the job should fail if vulnerabilities are found. 
- Based on *"severity_fail_cutoff"*
- `severity_fail_cutoff`| *(default: high)* | Set the severity level at which the job should fail.
=> Add New Input Variables

.github/workflows/platsec-security-scan-reusable-workflow.yml, false_positives/grype-false-positives.yml
This update enables the `Security GitHub Workflow` to use our False Positive Tracker ([grype-false-positives.yml](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/false_positives/grype-false-positives.yml)). 
Additionally, the output of both the `Syft` and `Grype` jobs provide `json` files in addition to the standard `text` files. These new `json` files provide more verbose data with regards to the SBOM and Vulnerability findings.
=> Refining False Positive Integration to the GH Workflow

false_positives/grype-false-positives.yml, false_positives/tattler-false-positives.json
Updating both FP Trackers to account for all system we scan are RHEL-Based
- `quay.io/repository/cloudservices` -  All quay images we scan are using UBI8 (RHEL)
- `version` - is commented out as images we scan are using UBI8 (RHEL) and have received security-backports
=> Update False Positives for all RHEL-Based Images

false_positives/tattler-false-positives.json
Update the `images` in the FP listing
- OLD: `quay.io/repository/cloudservices`
- NEW: `quay.io/cloudservices`
=> Fix Typo for FPs

jenkins/security-scan.sh
- Adds short git commit hash to image tag to avoid collisions on parallel runs
=> fix: add commit hash to image tag

jenkins/beta-testing-security-scan.sh
- Deactivates caching to avoid collisions when deleting the image built
- Rolls back change introduced in #38
=> Deactivate cache on podman builds

jenkins/security-scan.sh
Pushing @Victoremepunto updates from `Beta` to `Main`
----
[BETA] Deactivate cache on podman builds https://github.com/RedHatInsights/platform-security-gh-workflow/pull/39
- Deactivates caching to avoid collisions when deleting the image built
- Rolls back change introduced in https://github.com/RedHatInsights/platform-security-gh-workflow/pull/38
=> [Main Script] Deactivate cache on podman builds

jenkins/beta-testing-security-scan.sh, jenkins/security-scan.sh
The variables in the Jenkins Scripts (`main` & `beta`) have been moving to Initialize later in script's execution. There reason for this is due to the `DOCKERFILE_LOCATION` not being properly set if using a sub-directory in the `$TMP_JOB_DIR`.
=> Moving Jenkins Script Variables to Initialize Later in Execution

false_positives/grype-false-positives.yml, false_positives/tattler-false-positives.json
**False Addition:**
```
- vulnerability: 
CVE-2024-6345
GHSA-cx63-2mw6-8hw5
justification: 
Fixed (Backport)
https://access.redhat.com/security/cve/cve-2024-6345
package:
name: setuptools
type: python
location: "/usr/lib/python3.11/site-packages/*
```
=> Adding SetupTools FP for Python 3.11

jenkins/beta-testing-security-scan.sh
---
- **Syft** = `v0.94.0` -> `v1.12.2`
- **Grype** = `v0.74.4` -> `v0.80.1`
- Vulnerability Scanning has been updated to use the SBOM generated from `Syft` as opposed to reevaluating the whole image again when running `Grype`. The additional context from the `syft` SBOM allows for better performance and more accurate scans.
=> Update Syft and Grype Versions for Beta Testing

jenkins/beta-testing-security-scan.sh, jenkins/security-scan.sh
---
- **Syft** = `v0.94.0` -> `v1.12.2`
- **Grype** = `v0.74.4` -> `v0.80.1`
---
- Vulnerability Scanning has been updated to use the SBOM generated from `Syft` as opposed to reevaluating the whole image again when running `Grype`. The additional context from the `syft` SBOM allows for better performance and more accurate scans. 
- This update have been tested (and was successful) against repos using the `beta` version of the security-scanning script.
=> Update Syft and Grype Version for GL Jenkins Script

.github/workflows/platsec-security-scan-reusable-workflow.yml
---
- **Syft** = `v0.94.0` -> `v1.12.2`
- **Grype** = `v0.74.4` -> `v0.80.1`
---
- Vulnerability Scanning has been updated to use the SBOM generated from `Syft` as opposed to reevaluating the whole image again when running `Grype`. The additional context from the `syft` SBOM allows for better performance and more accurate scans.
=> Update Syft and Grype Version for GH Jobs

jenkins/beta-testing-security-scan.sh, jenkins/security-scan.sh
As part of updating the Builder stage images of our Go projects, we need to use images from brew, but the scanner fails as it can't pull the images. Should work with the registry creds
=> login to brew.registry.redhat.io

false_positives/grype-false-positives.yml
---
(CVE-2024-34158, CVE-2024-34156, CVE-2024-34155) detected within VMAAS. Grype is flagging 
stdlib as vulnerable within the dlv package. This package was patched as stated in RHSA-2024:6908.
-  Patched Version: delve-1.21.2-4
-  Detected Version: >= delve-1.22.1-1
REF: https://access.redhat.com/errata/RHSA-2024:6908
=> Update grype-false-positives in support of VMAAS

.github/workflows/platsec-security-scan-reusable-workflow.yml, jenkins/beta-testing-security-scan.sh
This pull request enhances the Security Workflow in both Git and Jenkins by adding new variables. The primary purpose of this update is to lock the URL used for installing the tools Syft and Grype, ensuring that only a trusted version is accessed during the curl request process. This measure increases security and reliability by preventing the potential installation of unverified versions.
- `SYFT_COMMIT_HASH`
- `GRYPE_COMMIT_HASH`
=> Updating Jobs to Support Git Commits on Anchore Tool Install

jenkins/beta-testing-security-scan.sh
The message `discovered vulnerabilities at or above the severity threshold` is vague and does not provide sufficient information to the user. 
This update allows for listing specific vulnerable packages identified in the `/artifacts/vulnerability-results-fixable-${IMAGE}.txt` artifact file before concluding the Jenkins Job within the console. This will give users a clearer understanding of which packages are affected, in addition to having the data in the artifact files.
=> [BETA] Adding Vulnerability Console Output to Jenkins Jobs

jenkins/security-scan.sh
The message `discovered vulnerabilities at or above the severity threshold` doesn't
really tell the user much - it's a good idea to then print out the vulnerable packages
found (from the artefact file) before exiting.
=> If grype fails, tell the user what was found

jenkins/security-scan.sh
This pull request enhances the Security Workflow in both Git and Jenkins by adding new variables. The primary purpose of this update is to lock the URL used for installing the tools Syft and Grype, ensuring that only a trusted version is accessed during the curl request process. This measure increases security and reliability by preventing the potential installation of unverified versions.
- `SYFT_COMMIT_HASH`
- `GRYPE_COMMIT_HASH`
=> [MAIN] Updating Jobs to Support Git Commits on Anchore Tool Install

false_positives/grype-false-positives.yml
**Vulnerability:** GHSA-93ww-43rr-79v3   (CVE-2024-10039)
**Reason:**  GHSA-93ww-43rr-79v3 (CVE-2024-10039) detected within RHBKC (KeyCloak). Grype is flagging the `keycloak-core` package as vulnerable. This package was patched as stated in `Red Hat build of KeyCloak - v24.0.9` patch notes.
-   Patched Version: 24.0.9
-   Detected Version: >= 24.0.10.redhat-00001
**REF:** https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html/release_notes/red_hat_build_of_keycloak_24_0#overview
**Package:**
-   **name:** keycloak-core
-   **version:** 24.0.10.redhat-00001
-   **type:** java-archive
-   **location:** "/opt/keycloak/lib/lib/main/org.keycloak.keycloak-core-24.0.10.redhat-00001.jar"
=> Adding RHBKC (KeyCloak) False-Positive

.github/workflows/platsec-security-scan-reusable-workflow.yml, .github/workflows/test_security-scan-workflow.yml
---
Adding the ability, within the GitHub Reusable Workflow,  to authenticate with the RH Catalog to pull base-image during the build process before scanning.
```
- name: Log in to Red Hat Catalog
run: |
if [[ -z "${{ secrets.RH_CATALOG_USERNAME }}" || -z "${{ secrets.RH_CATALOG_PASSWORD }}" ]]; then
echo "Skipping login: Red Hat credentials not set"
exit 0
fi
echo "${{ secrets.RH_CATALOG_USERNAME }}" | docker login 
registry.redhat.io -u "${{ secrets.RH_CATALOG_PASSWORD }}" --password-stdin
```
=> Adding RH Catalog Support to the Reusable Workflow

false_positives/grype-false-positives.yml
This PR fixes a parsing bug when parsing the `reason` field in the `grype-false-positives.yml`.
- Update the `reason` field in the `grype-false-positives.yml` to use `>-` as opposed to `>`.
-  `>` introduces a newline at the end of a string. 
- `>-` does **not** add a a newline at the end of a string
=> Removing the Inherent Newline in FP Reasons

.github/workflows/platsec-security-scan-reusable-workflow.yml, jenkins/beta-testing-security-scan.sh, jenkins/security-scan.sh
There is currently an issues is caused by an outage of the upstream SUSE DB (_Approximate start was Friday 2025-05-16. ETA fix, afternoon of 2025-05-21_). 
- [1] https://github.com/anchore/grype/issues/2674
- [2] https://bugzilla.suse.com/show_bug.cgi?id=1243337
The max age any data can be in the DB is 5 days (120h). So, it is jamming up the scans, because it is failing the DB age requirements.
This PR adds the following ENV VAR to the jobs to increase the max age for the DB data.
```
GRYPE_DB_MAX_ALLOWED_BUILT_AGE = 240h0m0s
```
=> Updating Max Grype DB Age to 10 days

jenkins/beta-testing-security-scan.sh, jenkins/security-scan.sh
There is currently an issues is caused by an outage of the upstream SUSE DB (_Approximate start was Friday 2025-05-16. ETA fix, afternoon of 2025-05-21_). 
- [1] https://github.com/anchore/grype/issues/2674
- [2] https://bugzilla.suse.com/show_bug.cgi?id=1243337
The max age any data can be in the DB is 5 days (120h). So, it is jamming up the scans, because it is failing the DB age requirements.
This PR adds the following ENV VAR to the jobs to increase the max age for the DB data.
```
GRYPE_DB_MAX_ALLOWED_BUILT_AGE = 240h0m0s
```
=> [Jenkins Jobs] Updating Max Grype DB Age to 10 days
